### PR TITLE
Feature: Added color support

### PR DESCRIPTION
**Pull request by magginichi**
Foreground and background color support for QrCodes including basic unit tests.

### CODE REVIEW

**Comment by manuelbl** [comment]
Thanks for the pull request. I had a quick look at it and I plan to integrate it with a few modifications.

In particular I would prefer if generating SVGs would not require System.Drawing.Common. Of course, the .NET library is needed as it is declared as a dependency. But System.Drawing.Common also has a dependency on native libraries that are only loaded if it is really used. These libraries are not necessarily present on macOS and Linux (incl. many CI/CD pipelines).

And what's the reason for raising the version number of the System.Drawing.Common dependency?

**Comment by magginichi** [comment]
Thanks for the info about System.Drawing.Common.
Do you plan to change the ToSvgString params from System.Drawing.Color to hex-color strings? I can implement that if you wish.
There's actually no reason about raising the version number about System.Drawing.Common dep. Commited that by accident, very sorry about that.

**Comment by manuelbl** [comment]
Sorry for the long delay.

Yes, the idea is to use hex color values instead of System.Drawing.Color. But I'm not yet sure if it should be strings like `#ff3bd3` (possibly including an alpha value as well), or an `uint` or even something else.

A string could be a good choice if it is possible to also specify SVG color names like `firebrick`.

If you want to, you can go ahead with these changes (incl. reverting the System.Drawing.Common version number).

**Comment by manuelbl** [comment]
Thanks for the contribution. I've integrated it into release 1.6.1.

For SVG grapics, the color can be specified as a string so that all CSS colors like "fuchsia", "rgba(34, 51, 203, 0.3)" etc. are available.

**Pull request closed without merging**
